# -*- coding: utf-8 -*-
"""CS378_Research_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nQbqnLFz4FizfkodQGAtV2Zip-9T6KO
"""



import sys
from codecarbon import track_emissions
@track_emissions()
def your_function_to_track():
  total = 0
  for i in range(1, sys.maxsize):
    total += i
  print(total)

your_function_to_track()